# Generated by Django 4.1.4 on 2023-09-06 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('veuf', 'Veuf'), ('marié', 'Marié'), ('célibataire', 'Célibataire')], default='célibataire', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Phone number can only contain digits.', regex='^\\d+$')]),
        ),
    ]
