# Generated by Django 4.2.5 on 2023-09-06 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0004_remove_profile_age_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
    ]
