# Generated by Django 4.2.5 on 2023-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0005_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(),
        ),
    ]
